### ISSUE TITLE
Error 401 while connecting to Twitter

### ISSUE THREAD

**Issue by s3bq8** [Ordisoftware/Tweets-Inspector#119]
hi i try fix with this but's the error connecting to Twitter still 

In case of error 404 or 403 while connecting to Twitter, the problem which is the timeout of the Twitter logged session in CefSharp not currently managed by the software - a trick for now is to erase this folder:
c:\Users\[name]\AppData\Roaming\Ordisoftware\Tweets Inspector\ChromiumCache\

**Comment by Ordisoftware** [comment]
Dear,

Have you defined Consumer Key, and Consumer Secret, and Back URL access rights (for example any domain belonging to you).

Using https://developer.twitter.com/en/apps or the new dev portal at https://developer.twitter.com/en/portal/.

It seems that the first simple system is abandoned for the second more complex and my account creation is in standby because I don't understand because I have no time and I am not currently working on this prototype project and I do not know if I will make it public with a v1.0 one day.

Best regards.

**Comment by s3bq8** [comment]
thanks for the reply, and I put everything you mentioned, but the program still does not work, it gives an error authenticating with twitter i will try

**Comment by Ordisoftware** [comment]
- Did you remove the ChromiumCache or is it not present?
- Does the internet browser open to Twitter login and allow you to authorize the app?

If it worked for you and not now, clearing ChromiumCache should work or there is some other problem.

The mockup is really experimental for a subject on which I start, and for lack of time I don't know what to do more immediately.

**Comment by s3bq8** [comment]
see this error 
![Capture5](https://user-images.githubusercontent.com/73422594/174445047-833f74a5-9dc6-46d3-b5d8-5a97bc4f180c.PNG)

**Comment by Ordisoftware** [comment]
It seems to be more about incorrect login info or bad keys, and not an outdated cefsharp cache for the login session. Hard to say more like that. Have you ever gotten from the software that it works? In case, can you put the previous box too or the full log, please.

**Comment by s3bq8** [comment]
When I press start
Go to this code
![Captures](https://user-images.githubusercontent.com/73422594/174446436-c6aa2581-3bf6-415a-86f0-9b24533935d7.PNG)

**Comment by Ordisoftware** [comment]
Have you ever gotten from the software that it works?

Either your credentials or keys are wrong or you need to delete the cefsharp cache which should be in `\AppData\Roaming\Ordisoftware\Tweets Inspector\ChromiumCache\` on Windows 10 x64 or elsewhere in case of a problem.

Since you are under VS: put a breakpoint at line 26 in WebBrowserForm.cs and see the path for `CachePath`.
